name: development pipeline

on:
  push:
    branches: master

jobs:
    build: 
      runs-on: ubuntu-latest

      steps: 
        - name: checkout code
          uses: actions/checkout@v2

        - name: setup node
          uses: actions/setup-node@v2
          with: 
            node-version: '16.x'
            
        - name: install dependencies
          run: yarn install

        - name: run test cases
          run: yarn test
    
  
